#!/bin/bash

# Clone the repo, bare mode
git clone --bare https://github.com/giovanebribeiro/dotfiles.git $HOME/.cfg

function config {
	/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME $@
}

mkdir -p .config-bkp
config checkout
if [ $? = 0 ]; then
	echo "Checked out config...";
else
	echo "Backup pre-existing dot files"
	config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .config-backup/{}
fi;
config checkout
config config status.showUntrackedFiles no

# Install dependencies per OS
echo "Install arch dependencies"
pgrep -x pacman > /dev/null && sudo pacman -Sy llvm-libs mesa rust alacritty bspwm sxhkd polybar feh autorandr xorg-xrandr
