#
# ~/.config/hypr/hypridle.conf
#

general {
    lock_cmd = pidof hyprlock || hyprlock
}

listener {
    # values in seconds
    timeout = 300
    on-timeout = loginctl lock-session
}

listener {
    timeout = 600
    on-timeout = systemctl suspend
}
