#
# Profile <nome_aqui>
# Antes de criar um novo profile:
# * instale o rclone
# * execute o `rclone config` para criar o REMOTE_NAME
#

# Diretório local da pasta a ser sincronizada
LOCAL_DIR=
# Nome da configuração remota do rclone
REMOTE_NAME=
# Diretório remoto a ser sincronizado
REMOTE_DIR=

